version: "3.8"

services:
  flaskapp:
    build: ./flaskapp
    container_name: flaskapp
    restart: always
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    volumes:
      - flaskapp_user:/flaskapp/user
    expose:
      - 8064

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  flaskapp_user: